version: '2'

services:
  web:
    image: nginx:alpine
    ports:
    - "80:80"
    volumes:
    - .:/usr/share/nginx/html
    - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
    - php
    - db
  php:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
    - .:/usr/share/nginx/html
  db:
    image: mysql:5.7
    ports:
    - "3306:3306"
    environment:
      MYSQL_DATABASE: "wp"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "secret"
      MYSQL_ROOT_PASSWORD: "secret"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
    - dbdata:/var/lib/mysql

volumes:
  dbdata:
