version: '3'

services:
  web:
    image: nginx:alpine
    ports:
    - "8000:80"
    volumes:
    - .:/usr/share/nginx/html
    - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
    - php
    - mysql
  php:
    image: php:4.9.8-php7.2--fpm
    volumes:
    - .:/usr/share/nginx/html
  mysql:
    image: mysql:5.7
    ports:
    - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
    volumes:
    - dbdata:/var/lib/mysql

volumes:
  dbdata: